name = "Hugo Sharecards"
license = "MIT"
licenselink = "https://github.com/fawkssc/hugo-sharecards/LICENSE"
description = "Updated image processing for share cards."
homepage = "https://github.com/fawkssc/hugo-sharecards"
tags = ["facebook", "opengraph", "twitter"]
features = []

[author]
  name = "Fawks Software Consulting"
  homepage = "https://www.fawkssoftwareconsulting.com"
