name = "Hugo Sharecards"
license = "MIT"
licenselink = "https://github.com/jefawks3/hugo-sharecards/LICENSE"
description = "Updated image processing for share cards."
homepage = "https://github.com/jefawks3/hugo-sharecards"
tags = ["facebook", "opengraph", "twitter"]
features = []

[author]
  name = "James Fawks"
  homepage = "https://jfawks.com"
